### ISSUE TITLE
老兄，你每个组件里都引入mixin，不闲麻烦吗！还有登录拦截，在每一个组件里判断，会死人的，为什么不在路由拦截里做呢！

### ISSUE THREAD

**Issue by LZVY** [Rosen97/web-shop#3]
@import '../../common/style/mixin';

**Comment by Rosen97** [comment]
对的，mixin可以全局引入，对于登录拦截最开始没考虑到在路由里判断，当然也可以。另外会持续优化的，项目体验不是太好，感谢issue！
